# Generated by Django 3.0.2 on 2020-01-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=255)),
                ('Date', models.DateField()),
                ('Amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='incomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=255)),
                ('Date', models.DateField()),
                ('Amount', models.FloatField()),
            ],
        ),
    ]
