# Generated by Django 3.0.2 on 2020-01-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetMS', '0002_auto_20200118_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='Type',
            new_name='Dept',
        ),
    ]
