# Generated by Django 3.0.2 on 2020-01-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetMS', '0003_auto_20200121_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Current', models.CharField(max_length=20)),
                ('Misc', models.IntegerField()),
                ('Marketing', models.IntegerField()),
                ('HR', models.IntegerField()),
                ('Finance', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
